spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/desafio_lanchonete_db
spring.datasource.username=lanchonete
spring.datasource.password=lanchonete

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

server.port=8082